[depot]
listen_address = ":5000"
repository_listing = true

[repositories]
    [repositories.maven-central-mirror]
    path = "/srv/maven/repository/central-mirror"

    [repositories.internal]
    path = "/srv/maven/repository/internal"
    deploy = true
    credentials = [
        "foo:bar"
    ]
